name: jiraulog
description: Controle de situação de obras e logística de materiais da Jirau.
publish_to: 'none'
version: 3.6.0+17

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  sqflite_common_ffi_web: ^1.1.2
  path: ^1.9.0
  intl: ^0.19.0
  file_picker: ^8.1.2
  spreadsheet_decoder: ^2.3.0
  pdf: ^3.11.1
  printing: ^5.13.4
  excel: ^4.0.6
  path_provider: ^2.1.4
  share_plus: ^10.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
